apiVersion: v1
kind: Pod
metadata:
  name: kubeflow-data-loader
  namespace: kubeflow
spec:
  containers:
  - name: loader
    image: busybox
    command: ["sleep", "36000"]
    volumeMounts:
    - mountPath: /data
      name: aml-storage
  volumes:
  - name: aml-storage
    persistentVolumeClaim:
      claimName: aml-data-pvc
